# Pipeline Parameters

data_collection:
  start_date: '2005-01-01'
  end_date: 'today'
  fred_series:
    - GDPC1
    - CPIAUCSL
    - UNRATE
    - FEDFUNDS
  companies:
    - JPM
    - BAC
    - AAPL
    - MSFT
    # ... add all 25

data_cleaning:
  reporting_lag_days: 45
  forward_fill_only: true
  outlier_threshold_iqr: 3.0

feature_engineering:
  lag_periods: [1, 5, 22]
  ma_windows: [30, 90]
  volatility_windows: [22, 90]

anomaly_detection:
  iqr_threshold: 3.0
  jump_threshold_pct: 50
  flag_only: true

bias_detection:
  representation_threshold: 0.3
  slicing_dimensions:
    - Company
    - Sector
    - TimePeriod

drift_detection:
  reference_period:
    start: 2005
    end: 2010
  current_period:
    start: 2020
    end: 2025
  significance_level: 0.05

alerts:
  slack_webhook: "https://hooks.slack.com/YOUR_WEBHOOK"  # ← UPDATE
  email_recipients:
    - "team@example.com"  # ← UPDATE